<?php

return [
    'base_url' => env('BIPAD_API_URL', 'https://bipadportal.gov.np/api/v1'),

    'endpoints' => [
        'incidents' => '/incident/',
        'alerts' => '/alert/',
        'hazards' => '/hazard/',
        'districts' => '/district/',
        'municipalities' => '/municipality/',
        'wards' => '/ward/',
    ],

    'sync' => [
        'interval_minutes' => (int) env('BIPAD_SYNC_INTERVAL_MINUTES', 1),
        'page_size' => (int) env('BIPAD_SYNC_PAGE_SIZE', 100),
        'timeout_seconds' => (int) env('BIPAD_SYNC_TIMEOUT', 60),
        'max_retries' => (int) env('BIPAD_SYNC_MAX_RETRIES', 3),
        'max_pages_recent' => (int) env('BIPAD_SYNC_MAX_PAGES_RECENT', 3),
        'hours_back' => (int) env('BIPAD_SYNC_HOURS_BACK', 6),
    ],

    'hazard_map' => [
        1  => ['type' => 'aircraft_accident',      'severity' => 'critical', 'category' => 'transport'],
        2  => ['type' => 'animal_incident',        'severity' => 'medium',   'category' => 'wildlife'],
        3  => ['type' => 'avalanche',              'severity' => 'critical', 'category' => 'natural'],
        4  => ['type' => 'boat_capsize',           'severity' => 'high',     'category' => 'transport'],
        5  => ['type' => 'bridge_collapse',        'severity' => 'critical', 'category' => 'infrastructure'],
        6  => ['type' => 'cold_wave',              'severity' => 'medium',   'category' => 'weather'],
        7  => ['type' => 'drowning',               'severity' => 'high',     'category' => 'water'],
        8  => ['type' => 'earthquake',             'severity' => 'critical', 'category' => 'geological'],
        9  => ['type' => 'epidemic',               'severity' => 'high',     'category' => 'health'],
        10 => ['type' => 'fire',                   'severity' => 'high',     'category' => 'fire'],
        11 => ['type' => 'flood',                  'severity' => 'critical', 'category' => 'water'],
        12 => ['type' => 'forest_fire',            'severity' => 'high',     'category' => 'fire'],
        13 => ['type' => 'hailstorm',              'severity' => 'medium',   'category' => 'weather'],
        14 => ['type' => 'heavy_rainfall',         'severity' => 'medium',   'category' => 'weather'],
        15 => ['type' => 'helicopter_crash',       'severity' => 'critical', 'category' => 'transport'],
        16 => ['type' => 'high_altitude',          'severity' => 'medium',   'category' => 'environmental'],
        17 => ['type' => 'landslide',              'severity' => 'high',     'category' => 'geological'],
        18 => ['type' => 'other_natural',          'severity' => 'medium',   'category' => 'natural'],
        19 => ['type' => 'rainfall',               'severity' => 'low',      'category' => 'weather'],
        20 => ['type' => 'snake_bite',             'severity' => 'medium',   'category' => 'wildlife'],
        21 => ['type' => 'snow_storm',             'severity' => 'high',     'category' => 'weather'],
        22 => ['type' => 'storm',                  'severity' => 'high',     'category' => 'weather'],
        23 => ['type' => 'thunderbolt',            'severity' => 'medium',   'category' => 'weather'],
        24 => ['type' => 'wind_storm',             'severity' => 'high',     'category' => 'weather'],
        25 => ['type' => 'drought',                'severity' => 'medium',   'category' => 'weather'],
        26 => ['type' => 'glacial_lake_outburst',  'severity' => 'critical', 'category' => 'water'],
        27 => ['type' => 'heat_wave',              'severity' => 'high',     'category' => 'weather'],
        28 => ['type' => 'inundation',             'severity' => 'high',     'category' => 'water'],
        29 => ['type' => 'soil_erosion',           'severity' => 'medium',   'category' => 'geological'],
        30 => ['type' => 'volcanic_eruption',      'severity' => 'critical', 'category' => 'geological'],
        31 => ['type' => 'industrial_disaster',    'severity' => 'high',     'category' => 'industrial'],
        32 => ['type' => 'mine_disaster',          'severity' => 'high',     'category' => 'industrial'],
        33 => ['type' => 'pandemics',              'severity' => 'critical', 'category' => 'health'],
        34 => ['type' => 'road_accident',          'severity' => 'high',     'category' => 'transport'],
        35 => ['type' => 'animal_flu',             'severity' => 'medium',   'category' => 'health'],
        36 => ['type' => 'deforestation',          'severity' => 'low',      'category' => 'environmental'],
        37 => ['type' => 'environmental_pollution','severity' => 'medium',   'category' => 'environmental'],
        38 => ['type' => 'famine',                 'severity' => 'critical', 'category' => 'health'],
        39 => ['type' => 'food_poisoning',         'severity' => 'medium',   'category' => 'health'],
        40 => ['type' => 'gas_explosion',          'severity' => 'critical', 'category' => 'industrial'],
        41 => ['type' => 'leakage_chemical',       'severity' => 'high',     'category' => 'industrial'],
        42 => ['type' => 'leakage_radiation',      'severity' => 'critical', 'category' => 'industrial'],
        43 => ['type' => 'leakage_toxic_gas',      'severity' => 'critical', 'category' => 'industrial'],
        44 => ['type' => 'microorganism_attack',   'severity' => 'high',     'category' => 'health'],
        45 => ['type' => 'other_non_natural',      'severity' => 'medium',   'category' => 'other'],
        46 => ['type' => 'water_accident',         'severity' => 'high',     'category' => 'water'],
        47 => ['type' => 'response_accident',      'severity' => 'medium',   'category' => 'other'],
    ],

    'source_type_map' => [
        'drr_api' => 'government',
        'nepal_police' => 'police',
        'community' => 'community',
        'other' => 'other',
    ],

    'alert_type_from_hazard' => [
        'fire' => 'emergency',
        'flood' => 'flood',
        'landslide' => 'landslide',
        'earthquake' => 'earthquake',
        'heavy_rainfall' => 'weather',
        'storm' => 'weather',
        'thunderbolt' => 'weather',
        'road_accident' => 'emergency',
        'snake_bite' => 'emergency',
        'epidemic' => 'emergency',
        'pandemics' => 'emergency',
        'drought' => 'weather',
        'avalanche' => 'landslide',
        'glacial_lake_outburst' => 'flood',
        'inundation' => 'flood',
        'boat_capsize' => 'emergency',
        'drowning' => 'emergency',
        'cold_wave' => 'weather',
        'heat_wave' => 'weather',
        'wind_storm' => 'weather',
        'hailstorm' => 'weather',
        'snow_storm' => 'weather',
        'forest_fire' => 'emergency',
        'industrial_disaster' => 'emergency',
        'gas_explosion' => 'emergency',
        'mine_disaster' => 'emergency',
        'leakage_chemical' => 'emergency',
        'leakage_radiation' => 'emergency',
        'leakage_toxic_gas' => 'emergency',
        'aircraft_accident' => 'emergency',
        'helicopter_crash' => 'emergency',
        'bridge_collapse' => 'emergency',
        'boat_capsize' => 'emergency',
        'road_accident' => 'emergency',
        'environmental_pollution' => 'emergency',
        'famine' => 'emergency',
        'food_poisoning' => 'emergency',
        'animal_flu' => 'emergency',
        'microorganism_attack' => 'emergency',
        'pandemics' => 'emergency',
        'other_natural' => 'emergency',
        'other_non_natural' => 'emergency',
        'high_altitude' => 'weather',
        'water_accident' => 'emergency',
        'response_accident' => 'emergency',
        'deforestation' => 'weather',
    ],

    'report_category_map' => [
        'fire' => 'Safety & Hazards',
        'forest_fire' => 'Safety & Hazards',
        'flood' => 'Safety & Hazards',
        'inundation' => 'Safety & Hazards',
        'glacial_lake_outburst' => 'Safety & Hazards',
        'landslide' => 'Safety & Hazards',
        'avalanche' => 'Safety & Hazards',
        'soil_erosion' => 'Safety & Hazards',
        'earthquake' => 'Safety & Hazards',
        'road_accident' => 'Road & Traffic',
        'snake_bite' => 'Safety & Hazards',
        'animal_incident' => 'Safety & Hazards',
        'animal_flu' => 'Safety & Hazards',
        'epidemic' => 'Safety & Hazards',
        'pandemics' => 'Safety & Hazards',
        'food_poisoning' => 'Safety & Hazards',
        'microorganism_attack' => 'Safety & Hazards',
        'famine' => 'Safety & Hazards',
        'boat_capsize' => 'Safety & Hazards',
        'drowning' => 'Safety & Hazards',
        'water_accident' => 'Safety & Hazards',
        'bridge_collapse' => 'Safety & Hazards',
        'industrial_disaster' => 'Safety & Hazards',
        'gas_explosion' => 'Safety & Hazards',
        'mine_disaster' => 'Safety & Hazards',
        'leakage_chemical' => 'Safety & Hazards',
        'leakage_radiation' => 'Safety & Hazards',
        'leakage_toxic_gas' => 'Safety & Hazards',
        'aircraft_accident' => 'Safety & Hazards',
        'helicopter_crash' => 'Safety & Hazards',
        'high_altitude' => 'Safety & Hazards',
        'deforestation' => 'Safety & Hazards',
        'response_accident' => 'Safety & Hazards',
        'other_natural' => 'General Information',
        'other_non_natural' => 'General Information',
    ],

    'report_subcategory_map' => [
        'fire' => 'Fire',
        'forest_fire' => 'Forest Fire',
        'flood' => 'Flood',
        'inundation' => 'Inundation',
        'glacial_lake_outburst' => 'Glacial Lake Outburst',
        'landslide' => 'Landslide',
        'avalanche' => 'Avalanche',
        'soil_erosion' => 'Soil Erosion',
        'earthquake' => 'Earthquake',
        'road_accident' => 'Road Accident',
        'snake_bite' => 'Snake Bite',
        'animal_incident' => 'Animal Attack',
        'animal_flu' => 'Animal Flu',
        'epidemic' => 'Epidemic',
        'pandemics' => 'Pandemic',
        'food_poisoning' => 'Food Poisoning',
        'microorganism_attack' => 'Microorganism Attack',
        'famine' => 'Famine',
        'boat_capsize' => 'Boat Capsize',
        'drowning' => 'Drowning',
        'water_accident' => 'Water Accident',
        'bridge_collapse' => 'Bridge Collapse',
        'industrial_disaster' => 'Industrial Disaster',
        'gas_explosion' => 'Gas Explosion',
        'mine_disaster' => 'Mine Disaster',
        'leakage_chemical' => 'Chemical Leakage',
        'leakage_radiation' => 'Radiation Leakage',
        'leakage_toxic_gas' => 'Toxic Gas Leakage',
        'aircraft_accident' => 'Aircraft Accident',
        'helicopter_crash' => 'Helicopter Crash',
        'high_altitude' => 'High Altitude Incident',
        'deforestation' => 'Deforestation',
        'response_accident' => 'Response Accident',
    ],

    // Hazard types to SKIP (don't create reports/alerts for these)
    'skip_hazard_types' => [
        'heavy_rainfall', 'storm', 'thunderbolt', 'wind_storm', 
        'hailstorm', 'snow_storm', 'cold_wave', 'heat_wave', 
        'drought', 'rainfall', 'high_altitude', 'environmental_pollution',
        'deforestation', 'famine', 'food_poisoning', 'animal_flu',
        'pandemics', 'microorganism_attack', 'other_natural', 
        'other_non_natural', 'response_accident',
        'flood', 'inundation',  // Weather/hydrological condition warnings
    ],

    // Only process reports within this many hours (real-time only)
    // Set to 720 (30 days) for testing with historical data; use 6 for production real-time
    'max_hours_old' => 720,
];