<?php

namespace Database\Seeders;

use App\Models\TranslationGlossary;
use Illuminate\Database\Seeder;

class AppUiWordSeeder extends Seeder
{
    /**
     * Common app UI words (English -> Nepali) used by the mobile app's
     * dictionary-driven localization. Admins can edit/override any of these
     * from the admin "Translator" page.
     */
    public function run(): void
    {
        $words = [
            // navigation & screens
            'Home' => 'गृह',
            'Places' => 'स्थानहरू',
            'Map' => 'नक्सा',
            'Alerts' => 'चेतावनीहरू',
            'Emergency' => 'आपतकालीन',
            'Reports' => 'रिपोर्टहरू',
            'Profile' => 'प्रोफाइल',
            'Settings' => 'सेटिङ्स',
            'Store' => 'पसल',
            'Leaderboard' => 'लिडरबोर्ड',
            'Assistant' => 'सहायक',
            'Search' => 'खोज',
            'Nearby' => 'नजिकका',
            'Featured' => 'विशेष',

            // auth
            'Login' => 'लगइन',
            'Register' => 'दर्ता गर्नुहोस्',
            'Sign in' => 'साइन इन',
            'Sign up' => 'साइन अप',
            'Logout' => 'लग आउट',
            'Welcome' => 'स्वागत छ',
            'Hello' => 'नमस्ते',
            'Name' => 'नाम',
            'Email' => 'इमेल',
            'Phone' => 'फोन',
            'Phone Number' => 'फोन नम्बर',
            'Password' => 'पासवर्ड',
            'Confirm Password' => 'पासवर्ड पुष्टि गर्नुहोस्',
            'Forgot Password?' => 'पासवर्ड बिर्सनुभयो?',
            'New Password' => 'नयाँ पासवर्ड',
            'Reset Password' => 'पासवर्ड रिसेट गर्नुहोस्',
            'Verify Email' => 'इमेल प्रमाणित गर्नुहोस्',
            'Verify' => 'प्रमाणित गर्नुहोस्',
            'Resend Code' => 'कोड फेरि पठाउनुहोस्',
            "Don't have an account?" => 'खाता छैन?',
            'Already have an account?' => 'पहिले नै खाता छ?',

            // actions
            'Save' => 'सुरक्षित गर्नुहोस्',
            'Cancel' => 'रद्द गर्नुहोस्',
            'Delete' => 'मेट्नुहोस्',
            'Confirm' => 'पुष्टि गर्नुहोस्',
            'OK' => 'ठिक छ',
            'Yes' => 'हो',
            'No' => 'होइन',
            'Retry' => 'पुनः प्रयास गर्नुहोस्',
            'Try Again' => 'फेरि प्रयास गर्नुहोस्',
            'Share' => 'साझा गर्नुहोस्',
            'Report' => 'रिपोर्ट',
            'Add' => 'थप्नुहोस्',
            'Edit' => 'सम्पादन गर्नुहोस्',
            'Update' => 'अद्यावधिक गर्नुहोस्',
            'Close' => 'बन्द गर्नुहोस्',
            'Send' => 'पठाउनुहोस्',
            'Submit' => 'पेश गर्नुहोस्',
            'Copy' => 'प्रतिलिपि गर्नुहोस्',
            'Back' => 'पछाडि',
            'Next' => 'अर्को',
            'Skip' => 'छोड्नुहोस्',
            'Done' => 'सम्पन्न',
            'Change' => 'परिवर्तन गर्नुहोस्',
            'Show More' => 'थप देखाउनुहोस्',
            'See More' => 'थप हेर्नुहोस्',
            'View All' => 'सबै हेर्नुहोस्',
            'Clear' => 'सफा गर्नुहोस्',
            'Open' => 'खोल्नुहोस्',
            'Filters' => 'फिल्टरहरू',

            // states & feedback
            'Loading' => 'लोड हुँदैछ',
            'Loading...' => 'लोड हुँदैछ...',
            'Error' => 'त्रुटि',
            'Failed' => 'असफल',
            'Success' => 'सफल',
            'Pending' => 'पर्खाइमा',
            'Active' => 'सक्रिय',
            'Inactive' => 'निष्क्रिय',
            'Completed' => 'पूरा भयो',
            'Expired' => 'म्याद सकिएको',
            'Available' => 'उपलब्ध',
            'Unavailable' => 'अनुपलब्ध',
            'Offline' => 'अफलाइन',
            'Online' => 'अनलाइन',
            'Unknown' => 'अज्ञात',
            'None' => 'कुनै पनि',
            'All' => 'सबै',
            'Other' => 'अन्य',
            'Today' => 'आज',
            'Yesterday' => 'हिजो',
            'Version' => 'संस्करण',

            // settings
            'Notifications' => 'सूचनाहरू',
            'Push Notifications' => 'पुश सूचनाहरू',
            'Email Notifications' => 'इमेल सूचनाहरू',
            'Alert Alerts' => 'चेतावनी सूचनाहरू',
            'Receive push notifications for alerts and updates' => 'चेतावनी र अपडेटका लागि पुश सूचना प्राप्त गर्नुहोस्',
            'Receive email updates about your reports' => 'तपाईंका रिपोर्टहरूबारे इमेल अपडेट प्राप्त गर्नुहोस्',
            'Get notified about critical alerts near you' => 'नजिकका गम्भीर चेतावनीहरूबारे सूचित हुनुहोस्',
            'Allow others to see your contributions on the map' => 'अरूलाई नक्सामा तपाईंका योगदानहरू देख्न दिनुहोस्',
            'Permanently delete your account and data' => 'तपाईंको खाता र डाटा स्थायी रूपमा मेट्नुहोस्',
            'Skip background map downloads and use less memory for images' => 'पृष्ठभूमि नक्सा डाउनलोड छोड्नुहोस् र छविहरूका लागि कम मेमोरी प्रयोग गर्नुहोस्',
            'Cache map tiles so the map works without internet' => 'नक्सा इन्टरनेट बिना चल्नका लागि टाइलहरू क्यास गर्नुहोस्',
            'Free up storage space (maps, places, images)' => 'भण्डारण स्थान खाली गर्नुहोस् (नक्सा, स्थानहरू, तस्बिरहरू)',
            'Clearing cache...' => 'क्यास खाली हुँदैछ...',
            'Cache cleared' => 'क्यास खाली भयो',
            'Your account has been deleted.' => 'तपाईंको खाता मेटिएको छ।',
            'Could not delete your account. Please try again.' => 'तपाईंको खाता मेट्न सकिएन। कृपया फेरि प्रयास गर्नुहोस्।',
            'Could not save settings. Please try again.' => 'सेटिङ्स सुरक्षित गर्न सकिएन। कृपया फेरि प्रयास गर्नुहोस्।',
            'Are you sure you want to delete your account? This action cannot be undone. All your data, reports, and contributions will be permanently removed.' => 'के तपाईं साँच्चै आफ्नो खाता मेट्न चाहनुहुन्छ? यो कार्य पूर्ववत् गर्न सकिँदैन। तपाईंका सबै डाटा, रिपोर्टहरू र योगदानहरू स्थायी रूपमा हटाइनेछन्।',
            'Appearance' => 'उपस्थिति',
            'Language' => 'भाषा',
            'Theme' => 'थिम',
            'Light' => 'उज्यालो',
            'Dark' => 'अँध्यारो',
            'System' => 'प्रणाली',
            'Privacy & Security' => 'गोपनीयता र सुरक्षा',
            'Show on Map' => 'नक्सामा देखाउनुहोस्',
            'Delete Account' => 'खाता मेट्नुहोस्',
            'Data & Storage' => 'डाटा र भण्डारण',
            'Data Saver Mode' => 'डाटा सेभर मोड',
            'Auto-download Maps' => 'स्वतः नक्सा डाउनलोड',
            'Clear Cache' => 'क्यास खाली गर्नुहोस्',
            'Settings saved' => 'सेटिङ्स सुरक्षित भयो',
            'Cache cleared' => 'क्यास खाली भयो',
            'About' => 'बारेमा',
            'Help' => 'सहायता',
            'Contact Us' => 'सम्पर्क गर्नुहोस्',
            'Terms of Service' => 'सेवाका सर्तहरू',
            'Privacy Policy' => 'गोपनीयता नीति',

            // alerts & emergency
            'Warning' => 'चेतावनी',
            'Danger' => 'खतरा',
            'Critical' => 'गम्भीर',
            'Information' => 'जानकारी',
            'Flood' => 'बाढी',
            'Earthquake' => 'भूकम्प',
            'Landslide' => 'पहिरो',
            'Strike' => 'हड्ताल',
            'Safe' => 'सुरक्षित',

            // places
            'Address' => 'ठेगाना',
            'Location' => 'स्थान',
            'Distance' => 'दूरी',
            'Category' => 'श्रेणी',
            'Rating' => 'मूल्याङ्कन',
            'Reviews' => 'समीक्षाहरू',
            'Comments' => 'टिप्पणीहरू',
            'Status' => 'स्थिति',
            'Verified' => 'प्रमाणित',
            'District' => 'जिल्ला',
            'Description' => 'विवरण',
            'Image' => 'तस्बिर',
            'Photos' => 'तस्बिरहरू',
            'Website' => 'वेबसाइट',
            'Add Place' => 'स्थान थप्नुहोस्',
            'Directions' => 'बाटो निर्देशन',
            'Route' => 'बाटो',
            'Start' => 'सुरु गर्नुहोस्',
            'Duration' => 'अवधि',
            'Hotel' => 'होटल',
            'Restaurant' => 'रेस्टुरेन्ट',
            'Cafes' => 'क्याफेहरू',
            'Attractions' => 'आकर्षणहरू',
            'Activities' => 'गतिविधिहरू',
            'Culture' => 'संस्कृति',
            'Adventure' => 'साहसिक',
            'Temple' => 'मन्दिर',
            'Mountain' => 'पहाड',
            'River' => 'नदी',
            'Lake' => 'ताल',
            'Forest' => 'जङ्गल',
            'City' => 'सहर',
            'Village' => 'गाउँ',

            // weather
            'Weather' => 'मौसम',
            'Temperature' => 'तापक्रम',
            'Rain' => 'वर्षा',
            'Wind' => 'हावा',
            'Humidity' => 'आर्द्रता',

            // rewards & gamification
            'Rewards' => 'पुरस्कारहरू',
            'Offers' => 'अफरहरू',
            'Points' => 'अंकहरू',
            'Rank' => 'क्रम',
            'Level' => 'स्तर',
            'Progress' => 'प्रगति',
            'Contributions' => 'योगदानहरू',
            'My Codes' => 'मेरा कोडहरू',
            'Code' => 'कोड',
            'Claim' => 'दाबी गर्नुहोस्',
            'Redeem' => 'रिडिम गर्नुहोस्',
            'Subscription' => 'सदस्यता',
            'Premium' => 'प्रिमियम',
            'Upgrade' => 'अपग्रेड गर्नुहोस्',
            'Plans' => 'योजनाहरू',
            'Price' => 'मूल्य',
            'Monthly' => 'मासिक',
            'Yearly' => 'वार्षिक',
            'Thanks' => 'धन्यवाद',

            // misc
            'Chat' => 'च्याट',
            'Type a message...' => 'सन्देश लेख्नुहोस्...',
            'Account' => 'खाता',
            'Travel' => 'यात्रा',
            'Tourism' => 'पर्यटन',
            'Population' => 'जनसंख्या',
            'Male' => 'पुरुष',
            'Female' => 'महिला',
            'Interests' => 'रुचिहरू',

            // Alert types
            'earthquake' => 'भूकम्प',
            'flood' => 'बाढी',
            'landslide' => 'पहिरो',
            'weather' => 'मौसम',
            'strike' => 'हड्ताल',
            'emergency' => 'आपतकालीन',

            // Alert severities
            'info' => 'जानकारी',
            'medium' => 'मध्यम',
            'high' => 'उच्च',
            'critical' => 'गम्भीर',

            // Alert UI phrases
            'Alert' => 'चेतावनी',
            'Alerts' => 'चेतावनीहरू',
            'Warning' => 'चेतावनी',
            'Emergency' => 'आपतकालीन',
            'New Alert' => 'नयाँ चेतावनी',
            'Near you' => 'तपाईं नजिक',
            'Alert created' => 'चेतावनी सिर्जना भयो',
            'New alert nearby' => 'नजिक नयाँ चेतावनी',
        ];

        foreach ($words as $term => $nepali) {
            TranslationGlossary::updateOrCreate(
                ['term' => $term],
                ['nepali' => $nepali, 'context' => 'ui', 'is_active' => true]
            );
        }
    }
}
